### ISSUE TITLE
Integrity check for firmware

### ISSUE THREAD

**Issue by jrahlf** [microsoft/uf2#17]
Hi,

I think it would be good to be able to check the integrity of the firmware to be flashed / is already flashed. Currently there is no checksum included in the UF2 structure.

**Comment by mmoskal** [comment]
There is support for MD5 checksum, see https://github.com/microsoft/uf2/blob/master/README.md#MD5 checksum

Did you want to use a different checksum? What is the specific scenario?

**Comment by jrahlf** [comment]
The MD5 checksum is good to prevent flashing invalid UF2 data.
However, if the flashing process was interrupted, then the firmware would be in parts new and in parts old, or let us say broken.

How do you make sure at startup, that the firmware to be booted is not corrupted?

**Comment by mmoskal** [comment]
Oh I guess you would need some application-specific solution - the application could do a checksum on start and compare.

**Comment by ladyada** [comment]
you cannot do a firmware verification without splitting the flash in two - this is done on some advanced bootloaders, but is not supported in UF2 - so its like DFU/Bossa/AVR/etc bootloaders where you can fail halfway thru the bootload process and get invalid code.

**Comment by mmoskal** [comment]
To be more precise, none of the current UF2 bootloaders do this sort of double-bank flash check. As for the file format itself, the MD5-checksum mechanism (or similar) could be used to implement such check.

**Comment by pieterconradie** [comment]
The issue has been closed, but here's my 2 cents: The vector table (Initial SP value and reset address) can be cached in RAM and written **after** the whole UF2 file has been received and written to FLASH. Before jumping to the app, integrity checks are performed (is SP and reset address values valid?). This prevents the partial upload issue. For example, see:
https://github.com/piconomix/piconomix-fwlib/blob/master/boards/arm/stm32/piconomix_hero_board/bootloaders/bootloader_usb_uf2/src/main.c

line 145-152, line 277 and finally line 93-120
