### ISSUE TITLE
JavaScript implementation for UF2

### ISSUE THREAD

**Issue by urish** [microsoft/uf2#40]
Hi, I have created a JavaScript library to read/write the UF2 format:

https://www.npmjs.com/package/uf2

It exports a function that can decode a UF2 block (given as a byte array), and another function that encodes a block.

For instance, the following Node.js code loads `blink.uf2` and prints the list of blocks in that files:

```javascript
const fs = require('fs');
const { decodeBlock, familyMap } = require('uf2');

const file = fs.openSync('blink.uf2');
const buffer = new Uint8Array(512);
while (fs.readSync(file, buffer) === buffer.length) {
  const block = decodeBlock(buffer);
  const family = familyMap.get(block.boardFamily) || 'unknown';
  const { totalBlocks, blockNumber, flashAddress, payload } = block;
  const hexAddress = '0x' + flashAddress.toString(16);
  console.log(`Block ${blockNumber + 1}/${totalBlocks} @${hexAddress}, Family: ${family}`);
  // Do something with payload...
}
fs.closeSync(file);
```

Sample output:

```
Block 1/50 @0x10000000, Family: Raspberry Pi RP2040
Block 2/50 @0x10000100, Family: Raspberry Pi RP2040
Block 3/50 @0x10000200, Family: Raspberry Pi RP2040
Block 4/50 @0x10000300, Family: Raspberry Pi RP2040
Block 5/50 @0x10000400, Family: Raspberry Pi RP2040
...
```

Additional examples are available in the [unit tests file](https://github.com/wokwi/uf2/blob/master/src/uf2.spec.ts#L82).

I hope you'll find it useful, and thank you for creating this very useful firmware file format :-)

**Comment by mmoskal** [comment]
Thank you, that looks useful! Added link.
