### ISSUE TITLE
Readme - Extensions tags example

### ISSUE THREAD

**Issue by JustAnother1** [microsoft/uf2#41]
The section states that the type of tag for "description of device" is 0x65**0d**9d In the example it is used but there(second line) it reads: "14 9d **9d** 65 ".

So either the tag type is 0x65**9d**9d or the example should be 14 9d **0d** 65....

Or did I miss understand something here?

**Comment by mmoskal** [comment]
Indeed a bug. To be clear, I changed the example bytes, not tag!
