### ISSUE TITLE
Add displaying of block header when converting uf2 to bin (family_id, flags, target_address, payload, etc..)

### ISSUE THREAD

**Issue by charkster** [microsoft/uf2#48]
Would it be possible to add the displaying of uf2 block header information when parsing a uf2 file? Additionally could there be a switch to just parse the provided uf2 file without conversion, in order to only display the block header information. If this is possible could the family_id short name also be displayed, otherwise I would still need to check the uf2families.json file.
uf2conv.py already parses uf2 files, so I was hoping this feature could be expanded.
Thanks.

**Comment by charkster** [comment]
I added 15 lines to uf2conv.py to implement the feature (mostly print statements). It uses the -i --info option.
Here is what it looks like:
```
--- UF2 File Header Info ---
Flag is 0x2000
Family ID is SAMD21, hex value is 0x68ed2b88
Target Address is 0x00002000
Number of blocks in file is 40, bin size is 10160 bytes
----------------------------
```

**Comment by mmoskal** [comment]
PR is most welcome!
