### ISSUE TITLE
uf2conv.py : wrong assert in calculation of upper address of hex format

### ISSUE THREAD

**Issue by elfmimi** [microsoft/uf2#53]
https://github.com/microsoft/uf2/blob/3016aec478e74f050420d3de3ddea1b939cb9e5c/utils/uf2conv.py#L180

instead segment address must be multiplied by 16 and added to each subsequent data record address.

cf. https://en.wikipedia.org/wiki/Intel_HEX

**Comment by mmoskal** [comment]
Not sure what this assert was doing there. The code already multiplies by 16 (by doing `<< 4`). Thanks!
