### ISSUE TITLE
uf2conv.py : Segment address of hex format must be added to address of each records

### ISSUE THREAD

**Issue by elfmimi** [microsoft/uf2#54]
Sorry, I should have provided more thorough description in the previous issue https://github.com/microsoft/uf2/issues/53 .

https://github.com/microsoft/uf2/blob/467cb3af6e01272fbce97ca0a1544fd3242a59c9/utils/uf2conv.py#L183

In this line above, it should be numerical addition.

so it must be like ...
```C
addr = upper + ((rec[1] << 8) | rec[2] )
```

> segment address must be multiplied by 16 and **added** to each subsequent data record address.

cf. https://en.wikipedia.org/wiki/Intel_HEX

**Comment by mmoskal** [comment]
Oh, I see, this is why the assertion was there :)

Fixed!
