### ISSUE TITLE
Likelihood of out of order block writes?

### ISSUE THREAD

**Issue by stuffmatic** [microsoft/uf2#78]
The [robustness](https://github.com/microsoft/uf2#robustness) section of the project readme states that the file format is designed to handle an OS writing blocks out of order. I'm curious to know how common this is and what specific operating systems do this.

**Comment by mmoskal** [comment]
It happened in macOS Ventura, though I believe it was patched by Apple as it broke micro:bit (which uses .hex). There also some issue with recent Windows pre-release updates, hopefully to be fixed. In short, in-order writes is not something I would rely on long-term.
